version: '3.8'

services:
  social-pulse:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./webdata:/app/webdata
      - ./.env:/app/.env
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - social-pulse

#  db:
#    image: postgres:13
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: social_pulse
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

#volumes:
#  postgres_data:
